### ISSUE TITLE
Remove settings.php from repository

### ISSUE THREAD

**Issue by nuez** [juampynr/DrupalCampSpain#3]
I think we ought to leave settings.php out of the repository, otherwise it won't install.

**Comment by juampynr** [comment]
That's not true. I have added the settings.php so we can keep there settings that apply to all environments, while [settings.local.php](https://github.com/juampynr/DrupalCampSpain/blob/master/web/sites/default/settings.php#L718) will contain local environment settings.

Can you verify that what I am saying is right @nuez? Please have a look and follow the installation instructions at https://github.com/juampynr/DrupalCampSpain.

**Comment by nuez** [comment]
Ok thanks juampy, I think I've misunderstood the use of settings.local.php, I'll try it again and get back to you

**Comment by nuez** [comment]
I think there is still an issue, described in https://www.drupal.org/node/728702. When copying the default.settings.local.php to settings.local.php and changing DB details to a local DB, we get an error. 

I think for now we can just change de README.md to point out that you have to go to core/install.php. I'll do that

**Comment by juampynr** [comment]
Sounds good! I left some in-line comments.

**Comment by juampynr** [comment]
https://github.com/juampynr/DrupalCampSpain/pull/4 got merged in.

@nuez, if you mention an issue in the pull request, it gets referenced automatically. See https://github.com/juampynr/DrupalCampSpain/pull/4.
