### ISSUE TITLE
Frontend Setup

### ISSUE THREAD

**Issue by nuez** [juampynr/DrupalCampSpain#5]
Setup base theme and Dcamp 2017 theme.

I've been looking at Omega 5, but don't see it's advantages over using Classy with a custom Libsass setup. I've been following the following presentation as a reference: https://docs.google.com/presentation/d/1EKLY_uaEqh4781O0TQSIS-ThV11yCVue6GTfCYm-3rI/edit#slide=id.ga1b0c001d_0_55

I propose the following themes:

- dcamp_base_theme (base theme classy)
- dcamp_2017_theme (base theme dcamp_base_theme)

With the following features: 

- Gulp + Sass + Libsass + Browsersync
- Fontello for Icons
- Prepared Favicons for all browsers (I think this has been an issue in the past versions).
- Very basic CSS setup and SMACSS Scaffolding.

**Comment by juampynr** [comment]
cc @ckrina, @capynet, @pakmanlh.

I don't have a strong opinion (nor a weak one) about this stuff.

**Comment by juampynr** [comment]
Note: we have merged https://github.com/juampynr/DrupalCampSpain/pull/6

**Comment by ckrina** [comment]
+1 to the current setup
